config/routes.rb
Rails.application.routes.draw do
  devise_for :designers, controllers: { registrations: "registrations" }
  devise_for :retailers, controllers: { registrations: "registrations" }
  # ALWAYS PUT ROOT ROUTE AT THE BEGINNING OF THE FILE
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

  # STATIC PAGES
  get '/buyers', to: 'pages#buyers'
  get '/designers/info', to: 'pages#designers', as: 'designers_info'
  get '/faq', to: 'pages#faq'
  get '/live_chat', to: 'pages#live_chat'
  get '/about', to: 'pages#about'

  # devise_for :retailers

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  resources :collections, only: [:show]

  resources :categories, only: [ :show ]

  resources :designers, only: [:show, :index] do
    resources :looks, only: [:show]
    resources :products, only: [:show]
  end
  resources :designers, only: [:edit, :update]

  resource :retailer, only: [:show, :edit, :update, :index]
  resource :store_collection, only: [:show, :new, :create, :edit, :update] do
    resources :store_products, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :designers
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :designer
  has_many :looks, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/models/designer.rb
class Designer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :collections, dependent: :destroy
  has_many :looks, dependent: :destroy
  has_many :products, dependent: :destroy
  has_and_belongs_to_many :categories
  has_attachment :profile_photo

  geocoded_by :city
  after_validation :geocode, if: :city_changed?
end

app/models/designer_order.rb
class DesignerOrder < ApplicationRecord
  belongs_to :store_collection
  has_many :order_products, dependent: :destroy
end

app/models/look.rb
class Look < ApplicationRecord
  belongs_to :collection
  belongs_to :designer
  has_many :look_products, dependent: :destroy
  has_many :products, through: :look_products
end

app/models/look_product.rb
class LookProduct < ApplicationRecord
  belongs_to :look
  belongs_to :product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :store_product
  belongs_to :designer_order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :collection
  belongs_to :designer
  has_many :look_products, dependent: :destroy
  has_many :looks, through: :look_products
  has_many :store_products, dependent: :destroy
  has_many :store_collections, through: :store_products
  has_attachments :photos, maximum: 2
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :store_collection, dependent: :destroy
  has_many :store_products, through: :store_collection
end

app/models/store_collection.rb
class StoreCollection < ApplicationRecord
  belongs_to :retailer
  has_many :designer_orders, dependent: :destroy
  has_many :store_products, dependent: :destroy
  has_many :products, through: :store_products
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :product
  belongs_to :store_collection
  has_many :order_products
end

app/controllers/designers_controller.rb
 class DesignersController < ApplicationController
  def show
    @designer = Designer.find(params[:id])
    session[:previous_page] = "designers#show"
  end

  def index
    @designers = Designer.paginate(page: params[:page], per_page: 6)
  end

  def edit
    @designer = Designer.find(params[:id])
  end

  def update
   @designer = Designer.find(params[:id])
   if @designer.update(designer_params)
    redirect_to designer_path(@designer)
   else
    render 'edit'
   end
  end

  private

   def designer_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:designer).permit(:first_name,:last_name, :brand, :age, :city, :profile_photo, :detail )
  end


end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  def show
    @look = Look.find(params[:id])
  end

  def index
    @look = Look.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @designers = Designer.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@designers) do |designer, marker|
      marker.lat designer.latitude
      marker.lng designer.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
      marker.infowindow "<div class='marker-card'> <a class='marker-link' href='#{designer_path(designer)}'>
      <img src='#{designer.profile_photo.fullpath}' alt='Profile picture' class='marker-image'/>
      <br> <h4 class='marker-text'>#{designer.brand}</h4> </a>
      </div>"
      marker.picture({
        url: "#{view_context.image_path 'favicon-16x16.png'}",
        width: 32,
        height: 32
        })

    end
  end

  def buyers
  end

  def designers
  end

  def about
  end

  def faq
  end

  def live_chat
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    session[:previous_page] = "products#show"
  end

  def index
    @products = Product.all
  end

  private

  def product_params
    params.require(:product).permit(:name, :detail, :color, :sizes, photos: [])
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  def show
    @retailer = Retailer.eager_load(store_collection: [store_products: [product: [:designer]]]).find(current_retailer.id)
    @store_products_grouped_by_designer = @retailer.store_products.group_by do |store_product|
      store_product.product.designer
    end
    session[:previous_page] = "retailers#show"
  end

  def index
    @retailers = Retailer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def prettify_text(text)
    result = ""
    text.split('\n').each do |block_of_text|
      result << "<p>#{block_of_text}</p>"
    end
    return result
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/retailers_helper.rb
module RetailersHelper
  def retailer_avatar_url(retailer)
    # return user.avatar.url if user.avatar.present?
    return retailer.profile_picture if retailer.profile_picture

    "default_user"
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= meta_title %></title>
  <%= favicon_link_tag 'favicon-32x32.png' %>
  <meta name="description" content="<%= meta_description %>">

  <!-- Facebook Open Graph data -->
  <meta property="og:title" content="<%= meta_title %>" />
  <meta property="og:type" content="website" />
  <meta property="og:url" content="<%= request.original_url %>" />
  <meta property="og:image" content="<%= meta_image %>" />
  <meta property="og:description" content="<%= meta_description %>" />
  <meta property="og:site_name" content="<%= meta_title %>" />

  <!-- Twitter Card data -->
  <meta name="twitter:card" content="summary_large_image">
  <meta name="twitter:site" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:title" content="<%= meta_title %>">
  <meta name="twitter:description" content="<%= meta_description %>">
  <meta name="twitter:creator" content="<%= DEFAULT_META["twitter_account"] %>">
  <meta name="twitter:image:src" content="<%= meta_image %>">
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <title>SpaceStation</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
</head>
<body class="<%= params[:controller] %>-<%= params[:action] %>">
  <%= render 'shared/flashes' %>
  <div class="container">
    <div class="row">
      <div class="col-xs-12">
        <%= render 'shared/navbar' %>
      </div>
    </div>
  </div>

  <%= yield %>
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <%= render 'shared/footer' %>
    </div>
  </div>
</div>

  <%= javascript_include_tag "https://maps.google.com/maps/api/js?libraries=places&key=#{ENV['GOOGLE_API_BROWSER_KEY']}" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/markerclusterer/src/markerclusterer_compiled.js" %>
  <%= javascript_include_tag "https://cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js" %>

  <%= javascript_include_tag 'application' %>
  <%= cloudinary_js_config %>
  <%= yield(:after_js) %>
</body>
</html>

app/views/shared/_banner.html.erb
<div class="banner banner-<%= banner_size %>" style="background-image: linear-gradient(180deg, rgba(69, 45, 19, 0.314) -14%, rgba(0, 39, 86, 0.314) 17%),url('https://sixtiescity.net/Fashion/stuff2102.jpg')";>
  <h1>
    <%= primary_header %>
  </h1>
  <p>
    <%= secondary_header %>
  </p>
  <!--  <a class="btn btn-primary btn-lg">Start now</a> -->
</div>

app/views/shared/_designercard.html.erb
<div class="designercard">

  <%= link_to designer_path(designer) do %>
  <div class="card-back">


  <% if !designer.collections.blank? %>
    <div class="card-back-image" style="background-image:url('<%= image_path designer.collections.last.products.first.picture_1  %>');"></div>
  <% end %>

  </div>


<% if !designer.profile_photo.blank? %>
  <div class="brand-content">
    <div class="brand-images">
    <div class="brand-avatar" style="background-image:url('<%= cl_image_path designer.profile_photo.path %>');">
    </div>
  <% if !designer.collections.blank? %>
    <div class="collection-photos">
      <% designer.collections.last.products.first(4).each do |product| %>
      <%= image_tag product.picture_1, width: 50 %>
      <% end %>
    </div>
  <% end %>

    </div>
    <div class="brandname">
      <%= designer.brand %> // <%= designer.city %>
    </div>
  </div>
<% end %>



  <% end %>

</div>

app/views/shared/_flashes.html.erb
<!-- app/views/shared/_flashes.html.erb -->
<div id="flashes">
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <%= alert %>
  </div>
<% end %>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
   <!--  This footer is made with <i class="fa fa-heart"></i> at Le Wagon -->
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-space-station">
  <div class="navbar-group-left">

    <% if retailer_signed_in? %>

    <ul class="list-inline flex-inline">
      <li>
        <div class="dropdown">
          <div class="avatar dropdown-toggle" style="background-image:url('<%= image_path retailer_avatar_url(current_retailer) %>');" data-toggle="dropdown"></div>

          <ul class="dropdown-menu dropdown-menu-left navbar-space-station-dropdown-menu">
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Account") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_retailer_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Invitations", "data-balloon-pos" => "down" do %>
        <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Messages", "data-balloon-pos" => "down" do %>
        <i class="fa fa-comments" aria-hidden="false"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Notifs", "data-balloon-pos" => "down" do %>
        <i class="fa fa-flag" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>

    <% elsif designer_signed_in? %>

    <ul class="list-inline flex-inline">
      <li>
        <div class="dropdown">
          <div class="avatar dropdown-toggle" style="background-image:url('<%= image_path retailer_avatar_url(current_designer) %>');" data-toggle="dropdown"></div>

          <ul class="dropdown-menu dropdown-menu-left navbar-space-station-dropdown-menu">
            <li>
              <%= link_to current_designer do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "Profile") %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Account") %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_designer_session_path, method: :delete do %>
              <i class="fa fa-sign-out"></i>  <%= t(".sign_out", default: "Log out") %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Invitations", "data-balloon-pos" => "down" do %>
        <i class="fa fa-star" aria-hidden="true"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Messages", "data-balloon-pos" => "down" do %>
        <i class="fa fa-comments" aria-hidden="false"></i>
        <% end %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link", "data-balloon" =>"Notifs", "data-balloon-pos" => "down" do %>
        <i class="fa fa-flag" aria-hidden="true"></i>
        <% end %>
      </li>
    </ul>

    <% else %>
    <ul class="list-inline">
      <li>
        <%= link_to "Buyers", buyers_path, class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "Designers", designers_path, class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "About us", about_path, class: "space-station-navbar-link"  %>
      </li>
    </ul>
    <% end %>
  </div>

  <div class="logo">
    <%= link_to root_path do %>
    <%= image_tag 'space_station.png' %>
    <% end %>
  </div>
  <div class= "navbar-group-right">


   <% if retailer_signed_in? %>
   <!-- Links when logged in -->
   <!-- Avatar with dropdown menu -->
   <div class="navbar-space-station-item navbar-collection">
    <ul class="list-inline">
      <li>
        <%= link_to "My Designers", "#", class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "Orders", "#", class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "Selections", retailer_path, class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link" do %>
        <i class="fa fa-shopping-cart"></i>
        <% end %>
      </li>
      <li>
        <div class="dropdown">
          <%= link_to "Help", "#", class: "space-station-navbar-link dropdown-toggle", "data-toggle" => "dropdown"  %>
          <ul class="dropdown-menu dropdown-menu-right navbar-space-station-dropdown-menu">
            <li>
              <%= link_to faq_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "FAQ") %>
              <% end %>
            </li>
            <li>
              <%= link_to live_chat_path do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Live Chat") %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>

  <% elsif designer_signed_in? %>
   <!-- Links when logged in -->
   <!-- Avatar with dropdown menu -->
   <div class="navbar-space-station-item navbar-collection">
    <ul class="list-inline">
      <li>
        <%= link_to "Orders", "#", class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "Collections", "#", class: "space-station-navbar-link"  %>
      </li>
      <li>
        <%= link_to "#", class: "space-station-navbar-link" do %>
        <i class="fa fa-shopping-cart"></i>
        <% end %>
      </li>
      <li>
        <div class="dropdown">
          <%= link_to "Help", "#", class: "space-station-navbar-link dropdown-toggle", "data-toggle" => "dropdown"  %>
          <ul class="dropdown-menu dropdown-menu-right navbar-space-station-dropdown-menu">
            <li>
              <%= link_to faq_path do %>
              <i class="fa fa-user"></i> <%= t(".profile", default: "FAQ") %>
              <% end %>
            </li>
            <li>
              <%= link_to live_chat_path do %>
              <i class="fa fa-home"></i>  <%= t(".profile", default: "Live Chat") %>
              <% end %>
            </li>
          </ul>
        </div>
      </li>
    </ul>
  </div>


  <% else %>
  <!-- Login link (when logged out) -->
  <div class = "dropdown">
    <%= link_to "LOG IN", "#", class: "space-station-navbar-link dropdown-toggle", "data-toggle" => "dropdown" %>
    <ul class="dropdown-menu">
      <li>
        <%= link_to t(".sign_in", default: "Retailer Login"), new_retailer_session_path %>
      </li>
      <li>
        <%= link_to t(".sign_in", default: "Designer Login"), new_designer_session_path %>
      </li>
    </ul>
  </div>

  <div class = "dropdown">
  <%= link_to "Request membership", "#", class: "btn-space-station space-station-navbar-link dropdown-toggle", "data-toggle" => "dropdown"  %>
  <ul class="dropdown-menu dropdown-menu-right">
    <li>
      <%= link_to "As Retailer", new_retailer_registration_path %>
    </li>
    <li>
      <%= link_to "As Designer", new_designer_registration_path %>
    </li>
  </ul>
  <% end %>
  </div>
</div>
</div>
</div>

<% unless params[:controller] == "pages" && params[:action] == "home" %>
<%= render partial: 'shared/banner', locals: {
  primary_header: "",
  secondary_header: "",
  # image: "https://images4.alphacoders.com/153/153316.jpg",
  image: "http://4.bp.blogspot.com/_99U_pO3l2-Y/SSQqaBUFa-I/AAAAAAAAAOk/yFfmxl6sZdw/w1200-h630-p-k-no-nu/cardinall2.jpg",
  banner_size: "quarter"
} %>

<% end %>

app/views/shared/_product_card.html.erb
<%= link_to designer_product_path(product.designer, product) do %>
  <div class="product-card product-card-high" data-product='<%= product.id %>'>
    <div class="product-image product-image-tall" style="background-image:url('<%= image_url product.picture_1, crop: :fill %>');">

      <%= render 'shared/star', product: product %>

    </div>
    <div class="product-details">
      <p>
        <strong>
          <%=product.name%>
        </strong>
        <%= truncate product.detail, length: 50%>
      </p>
      <div class="product-footer">
        <div class="price">
          $<%= product.price %>
        </div>
        <div class="rrp">
          RRP: $<%= product.price*2 %>
        </div>
      </div>
    </div>
  <div id="product-notice-<%= product.id %>"></div>
  </div>
<% end %>

app/views/shared/_star.html.erb
<% if current_retailer %>

<% if StoreProduct.pluck(:product_id).include?(product.id) %>
  <%= simple_form_for :product, url: store_collection_store_product_path(product), method: :delete, remote: true do |f| %>
    <label for="destroy-<%= product.id %>">
     <i class="fa fa-star selected" aria-hidden="true"></i>
    </label>
    <input type="submit" name="commit" id="destroy-<%= product.id %>" value="Remove" class="hidden" data-disable-with="Remove">
  <% end %>
<% else %>
  <%= simple_form_for :product, url: store_collection_store_products_path(product_id: product.id), remote: true do |f| %>
    <label for="submit-<%= product.id %>">
      <i class="fa fa-star" aria-hidden="true"></i>

    </label>
    <input type="submit" id="submit-<%= product.id %>" name="commit" value="Add to Selections" class="hidden" data-disable-with="Add to Selections">
  <% end %>
<% end %>

<% end %>