config/routes.rb
Rails.application.routes.draw do
  devise_for :designers, controllers: { registrations: "registrations" }
  devise_for :retailers, controllers: { registrations: "registrations" }
  # ALWAYS PUT ROOT ROUTE AT THE BEGINNING OF THE FILE
  root to: 'pages#home'
  mount Attachinary::Engine => "/attachinary"

  # STATIC PAGES
  get '/buyers', to: 'pages#buyers'
  get '/designers/info', to: 'pages#designers', as: 'designers_info'
  get '/faq', to: 'pages#faq'
  get '/live_chat', to: 'pages#live_chat'
  get '/about', to: 'pages#about'

  # devise_for :retailers

  get 'contact', to: 'pages#contact'
  get 'about', to: 'pages#about'

  resources :collections, only: [:show]

  resources :categories, only: [ :show ]

  resources :designers, only: [:show, :index] do
    resources :looks, only: [:show]
    resources :products, only: [:show]
  end
  resources :designers, only: [:edit, :update]

  resource :retailer, only: [:show, :edit, :update, :index]
  resource :store_collection, only: [:show, :new, :create, :edit, :update] do
    resources :store_products, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :designers
end

app/models/collection.rb
class Collection < ApplicationRecord
  belongs_to :designer
  has_many :looks, dependent: :destroy
  has_many :products, dependent: :destroy
end

app/models/designer.rb
class Designer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :collections, dependent: :destroy
  has_many :looks, dependent: :destroy
  has_many :products, dependent: :destroy
  has_and_belongs_to_many :categories
  has_attachment :profile_photo

  geocoded_by :city
  after_validation :geocode, if: :city_changed?
end

app/models/designer_order.rb
class DesignerOrder < ApplicationRecord
  belongs_to :store_collection
  has_many :order_products, dependent: :destroy
end

app/models/look.rb
class Look < ApplicationRecord
  belongs_to :collection
  belongs_to :designer
  has_many :look_products, dependent: :destroy
  has_many :products, through: :look_products
end

app/models/look_product.rb
class LookProduct < ApplicationRecord
  belongs_to :look
  belongs_to :product
end

app/models/order_product.rb
class OrderProduct < ApplicationRecord
  belongs_to :store_product
  belongs_to :designer_order
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :collection
  belongs_to :designer
  has_many :look_products, dependent: :destroy
  has_many :looks, through: :look_products
  has_many :store_products, dependent: :destroy
  has_many :store_collections, through: :store_products
  has_attachments :photos, maximum: 2
end

app/models/retailer.rb
class Retailer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :store_collection, dependent: :destroy
  has_many :store_products, through: :store_collection
end

app/models/store_collection.rb
class StoreCollection < ApplicationRecord
  belongs_to :retailer
  has_many :designer_orders, dependent: :destroy
  has_many :store_products, dependent: :destroy
  has_many :products, through: :store_products
end

app/models/store_product.rb
class StoreProduct < ApplicationRecord
  belongs_to :product
  belongs_to :store_collection
  has_many :order_products
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def default_url_options
    { host: ENV["HOST"] || "localhost:3000" }
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @category = Category.find(params[:id])
  end
end

app/controllers/designers_controller.rb
 class DesignersController < ApplicationController
  def show
    @designer = Designer.find(params[:id])
    session[:previous_page] = "designers#show"
  end

  def index
    @designers = Designer.paginate(page: params[:page], per_page: 6)
  end

  def edit
    @designer = Designer.find(params[:id])
  end

  def update
   @designer = Designer.find(params[:id])
   if @designer.update(designer_params)
    redirect_to designer_path(@designer)
   else
    render 'edit'
   end
  end

  private

   def designer_params
    # *Strong params*: You need to *whitelist* what can be updated by the user
    # Never trust user data!
    params.require(:designer).permit(:first_name,:last_name, :brand, :age, :city, :profile_photo, :detail )
  end


end

app/controllers/looks_controller.rb
class LooksController < ApplicationController
  def show
    @look = Look.find(params[:id])
  end

  def index
    @look = Look.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    @designers = Designer.where.not(latitude: nil, longitude: nil)

    @hash = Gmaps4rails.build_markers(@designers) do |designer, marker|
      marker.lat designer.latitude
      marker.lng designer.longitude
      # marker.infowindow render_to_string(partial: "/flats/map_box", locals: { flat: flat })
      marker.infowindow "<div class='marker-card'> <a class='marker-link' href='#{designer_path(designer)}'>
      <img src='#{designer.profile_photo.fullpath}' alt='Profile picture' class='marker-image'/>
      <br> <h4 class='marker-text'>#{designer.brand}</h4> </a>
      </div>"
      marker.picture({
        url: "#{view_context.image_path 'favicon-16x16.png'}",
        width: 32,
        height: 32
        })

    end
  end

  def buyers
  end

  def designers
  end

  def about
  end

  def faq
  end

  def live_chat
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def show
    @product = Product.find(params[:id])
    session[:previous_page] = "products#show"
  end

  def index
    @products = Product.all
  end

  private

  def product_params
    params.require(:product).permit(:name, :detail, :color, :sizes, photos: [])
  end
end

app/controllers/retailers_controller.rb
class RetailersController < ApplicationController
  def show
    @retailer = Retailer.eager_load(store_collection: [store_products: [product: [:designer]]]).find(current_retailer.id)
    @store_products_grouped_by_designer = @retailer.store_products.group_by do |store_product|
      store_product.product.designer
    end
    session[:previous_page] = "retailers#show"
  end

  def index
    @retailers = Retailer.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def prettify_text(text)
    result = ""
    text.split('\n').each do |block_of_text|
      result << "<p>#{block_of_text}</p>"
    end
    return result
  end
end

app/helpers/meta_tags_helper.rb
module MetaTagsHelper
  def meta_title
    content_for?(:meta_title) ? content_for(:meta_title) : DEFAULT_META["meta_title"]
  end

  def meta_description
    content_for?(:meta_description) ? content_for(:meta_description) : DEFAULT_META["meta_description"]
  end

  def meta_image
    meta_image = (content_for?(:meta_image) ? content_for(:meta_image) : DEFAULT_META["meta_image"])
    # little twist to make it work equally with an asset or a url
    meta_image.starts_with?("http") ? meta_image : image_url(meta_image)
  end
end

app/helpers/retailers_helper.rb
module RetailersHelper
  def retailer_avatar_url(retailer)
    # return user.avatar.url if user.avatar.present?
    return retailer.profile_picture if retailer.profile_picture

    "default_user"
  end
end

app/views/categories/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">


<div class="designers-search-display">

<div class="search-col-container">
   <%= link_to "All Designers", designers_path %>
   <h4 class="text-center">Regions</h4>
  <ul>
    <li>Africa</li>
    <li>Asia</li>
    <li>North America</li>
    <li>Central America</li>
    <li>South America</li>
    <li>Middle East</li>
    <li>Europe</li>
    <li>Oceania</li>
  </ul>

  <h4 class='text-center'>Categories</h4>
  <ul>
    <% Category.all.each do |category| %>
      <li> <%= link_to category.title, category_path(category)  %> </li>
    <% end %>
  </ul>


    <h4 class="text-center">Styles</h4>
  <ul>
    <li>Bohemian</li>
    <li>Dandy</li>
    <li>Minimalist</li>
    <li>Smart</li>
    <li>Casual/Street</li>
    <li>Couture</li>
    <li>Vintage</li>
    <li>Preppy</li>
    <li>Androgynous</li>
  </ul>
</div>


<div class="designer-container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center with-underline"><%= @category.title %></h1>
    </div>
  </div>
  <!-- For all designers -> make a designer card -->
  <div class="row">
    <% @category.designers.each do |d| %>
    <div class="col-xs-12 col-md-6">
      <%= render 'shared/designercard', designer: d %>
    </div>
    <% end %>
  </div>
</div>

</div>
    </div>
  </div>
</div>




<!-- Designer.where {designer.categories.includes? { category.title == 'Menswear' }} -->

app/views/designers/_content.html.erb
  <div class = "collection-header">
    <h2 class="text-center">
     <%= @designer.brand %>
   </h2>
   <p class="long-text">
    <%= prettify_text(@designer.detail).lstrip.html_safe %>
  </p>
</div>
<div class="cards-container">

  <div id="collection_preview">
    <%= render 'collections/preview', collection: @designer.collections.last %>
  </div>

</div>

app/views/designers/_sidebar.html.erb
  <div class="first-section">

  <h2>
    <%=@designer.brand %>
  </h2>
  <ul class="list-unstyled bio-box">
    <li class="brand">
     Contact person: <%= @designer.first_name%> <%= @designer.last_name %>
   </li>
   <li>
     <span class="city"><%= @designer.city %></span> - <span class="year"><%= @designer.age %></span>
   </li>
  <li class="description">
    <p class="long-text">
      <%= truncate @designer.detail, length: 150 %>
    </p>
  </li>
</ul>

  <div class="bio-image-sidebar" style="background-image:url('<%= cl_image_path @designer.profile_photo.path %>');">
  </div>
</div>

<em>
<p> <strong>Tags:</strong> <% @designer.categories.each do |category|  %>
  <%= link_to category.title, category_path(category)%>
  <% end %>
</p>
<p> <strong>Main markets: Europe, Middle East</strong>
  </p>
</em>



<div class="second-section">
  <h4>
    collections
  </h4>
  <ul>
     <% @designer.collections.each do |collection| %>
      <li>
        <%= link_to "#{collection.season} #{collection.year}", collection_path(collection), remote: true  %>
      </li>
    <% end %>
  </ul>


  <h4>
    preferences
  </h4>
  <ul>
    <li>
      <strong>Price:  </strong>$$
    </li>
    <li>
      <strong>Method:  </strong>F.O.B
    </li>
      <li>
      <strong>MOQ:  </strong>$3,000
    </li>
  </ul>

  <h4>
    products
  </h4>
  <ul>
    <li>
     Jackets
    </li>
    <li>
      Suits
    </li>
    <li>
      Sweaters
    </li>
    <li>knitwear</li>
    <li>shirts</li>
    <li>t-shirts</li>
    <li>trousers</li>
    <li>sneakers</li>
    <li>shoes</li>
    <li>bags</li>
    <li>hats</li>
    <li>accessories</li>
  </ul>

  <% if current_designer == @designer %>
  <%= link_to edit_designer_path(current_designer) do %>
    <input  id="connect-btn" type="submit" value= "Update" class="btn-space-station">
  <% end %>
  <% else %>
    <input  id="connect-btn" type="submit" value="Connect" class="btn-space-station">
  <% end %>

</div>

app/views/designers/edit.html.erb
<h1>Designer profile</h1>

<div class="form">

<%= simple_form_for(@designer) do |f| %>

  <%= f.input :first_name %>
  <%= f.input :last_name %>
  <%= f.input :brand %>
  <%= f.input :age %>
  <%= f.input :city %>
  <%= f.input :detail %>
  <%= f.input :profile_photo, as: :attachinary %>

 <!--  as: :attachinary %> -->
  <%= f.button :submit %>
<% end %>

</div>

app/views/designers/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">


<div class="designers-search-display">
<div class="search-col-container">
   <h4 class="text-center">Regions</h4>
  <ul>
    <li>Africa</li>
    <li>Asia</li>
    <li>North America</li>
    <li>Central America</li>
    <li>South America</li>
    <li>Middle East</li>
    <li>Europe</li>
    <li>Oceania</li>
  </ul>

  <h4 class='text-center'>Categories</h4>
  <ul>
    <% Category.all.each do |category| %>
      <li> <%= link_to category.title, category_path(category)  %> </li>
    <% end %>
  </ul>


    <h4 class="text-center">Styles</h4>
  <ul>
    <li>Bohemian</li>
    <li>Dandy</li>
    <li>Minimalist</li>
    <li>Smart</li>
    <li>Casual/Street</li>
    <li>Couture</li>
    <li>Vintage</li>
    <li>Preppy</li>
    <li>Androgynous</li>
  </ul>
</div>


<div class="designer-container">
  <div class="row">
    <div class="col-xs-12">
      <h1 class="text-center with-underline">All Designers</h1>
    </div>
  </div>
  <!-- For all designers -> make a designer card -->
  <div class="row">
    <% @designers.each do |d| %>
    <div class="col-xs-12 col-md-6">
      <%= render 'shared/designercard', designer: d %>
    </div>
    <% end %>
  </div>
  <div class="pagination-container">
    <%= will_paginate @posts %>
    </div>
</div>

</div>
    </div>
  </div>
</div>

app/views/designers/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12">
      <div class="breadcrumbs">
        <%= link_to "Designers", designers_path %> > <%= @designer.brand %>
      </div>
    </div>
    <div class="col-xs-12">
      <div class="two-column-layout-container">

        <div class="sidebar">
          <%= render partial: 'sidebar' %>
        </div>

        <div class="content">
          <%= render partial: 'content' %>
        </div>

      </div>




    </div>
  </div>
</div>

app/views/looks/index.html.erb
<h1>Looks#index</h1>
<p>Find me in app/views/looks/index.html.erb</p>

app/views/looks/show.html.erb
<h1>Looks#show</h1>
<p>Find me in app/views/looks/show.html.erb</p>

app/views/products/_product_information.html.erb
<div class= "product-titles">
  <h2 class="text-center"><%= product.designer.brand%></h2>
  <h3 class="text-center"> <%= product.name %> </h3>
</div>
<div class="product-info">
  <strong>Collection:</strong> <%= product.collection.detail %> <br>
  <strong>Comes in sizes:</strong> <%= product.sizes %> <br>
  <strong>Color:</strong> <%= product.color %> <br>
  <strong>Detail:</strong> <%= product.detail %> <br>
  <strong>Wholesale price:</strong> $<%= product.price %> <br>
  <strong>RRP: </strong> $<%= product.price*2 %>

</div>
<div class="btn-add-to-selections">
  <% if current_retailer %>
    <% if StoreProduct.pluck(:product_id).include?(product.id) %>
    <%= simple_form_for :product, url: store_collection_store_product_path(product), method: :delete do |f| %>
        <%= f.submit "Remove", class: "btn-space-station" %>
      <% end %>
    <% else %>
      <%= simple_form_for :product, url: store_collection_store_products_path(product_id: product.id) do |f| %>
        <%= f.submit "Add to Selections", class: "btn-space-station" %>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/products/_product_pictures.html.erb
<% unless @product.picture_1.blank? %>
<div class="col-xs-12 col-lg-4">

  <div class="product-card">
    <div class="product-image product-image-small" data-target="<%= image_path @product.picture_1 %>" style="background-image:url('<%= image_url @product.picture_1, crop: :fill %>');"></div>
  </div>
</div>
<% end %>

  <% unless @product.picture_2.blank? %>
  <div class="col-xs-12 col-lg-4">

    <div class="product-card">
      <div class="product-image product-image-small" data-target="<%= image_path @product.picture_2 %>" style="background-image:url('<%= image_url @product.picture_2, crop: :fill %>');"></div>
    </div>

  </div>
  <% end %>


  <% unless @product.picture_3.blank? %>
  <div class="col-xs-12 col-lg-4">

    <div class="product-card">
      <div class="product-image product-image-small" data-target="<%= image_path @product.picture_3 %>" style="background-image:url('<%= image_url @product.picture_3, crop: :fill %>');"></div>
    </div>
  </div>
  <% end %>


  <% unless @product.picture_4.blank? %>
  <div class="col-xs-12 col-lg-4">

    <div class="product-card">
      <div class="product-image product-image-small" data-target="<%= image_path @product.picture_4 %>" style="background-image:url('<%= image_url @product.picture_4, crop: :fill %>');"></div>
    </div>

  </div>
  <% end %>

app/views/products/_productform.html.erb
<%= f.input :photo, as: :attachinary %>

app/views/products/index.html.erb
<h1>Products#index</h1>
<p>Find me in app/views/products/index.html.erb</p>

app/views/products/show.html.erb
<div class="container">
  <div class="breadcrumbs">
        <%= link_to "Designers", designers_path %> > <%= link_to @product.designer.brand, designer_path(@product.designer)  %>
      </div>
  <div class="row">
    <div class="col-xs-6">
      <div id="highlight" class="product-highlight-picture" style="background-image:url('<%= image_path @product.picture_1 %>');">
      </div>
    </div>
    <div class="col-xs-6">
      <div class="product-header">
        <%= render partial: 'product_information', locals: { product: @product} %>
      </div>
      <div class="row">
        <%= render partial: "product_pictures", locals: { product: @product } %>
      </div>
    </div>
  </div>
</div>